# This workflow will build a package using Maven and then test it
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run Maven Tests on Push To Main

# This section specifies when this workflow is triggered
# Here, we specify that it is triggered whenever there is a push to the `main` branch.
on:
  push:
    branches:
      - main

# This section specifies the jobs/steps to be executed in the workflow
jobs:
  # This workflow only has a single job
  build:
    name: Build, test and Package Application
    runs-on: ubuntu-latest
    # Here are the steps to be executed by the machine running this job
    steps:
      # Checkout the GitHub repository with the code
      - name: Checkout Repository
        uses: actions/checkout@v2

        # Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
          check-latest: true

        # Run our tests. Whether they pass/fail will be reflected on the workflow status badge.
      - name: Build and test with Maven
        run: mvn -B package
